spring:
  application:
    name: preprocessing
  profiles:
    active: "dev"

server:
  port: ${PORT:9014}

---
spring:
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitUser
    password: rabbitPass
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    
---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitUser
    password: rabbitPass
eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistration:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true